# Generated by Django 2.0.7 on 2018-07-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180702_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speaker',
            old_name='name',
            new_name='fullName',
        ),
        migrations.AddField(
            model_name='speaker',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='speaker',
            name='imageLoc',
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AddField(
            model_name='speaker',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='title',
            field=models.CharField(blank=True, max_length=63),
        ),
    ]
