# Generated by Django 2.0.7 on 2018-07-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_panel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breakout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=63)),
                ('roomNum', models.CharField(blank=True, max_length=63)),
                ('imageLoc', models.CharField(blank=True, max_length=63)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
