# Generated by Django 2.0.7 on 2018-07-03 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_breakout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=63)),
                ('bio', models.CharField(blank=True, max_length=63)),
                ('company', models.CharField(blank=True, max_length=63)),
                ('image_loc', models.CharField(blank=True, max_length=63)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=63)),
                ('session_type', models.CharField(blank=True, max_length=63)),
                ('image_loc', models.CharField(blank=True, max_length=63)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('room_num', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Breakout',
        ),
        migrations.DeleteModel(
            name='Panel',
        ),
        migrations.DeleteModel(
            name='Speaker',
        ),
        migrations.AddField(
            model_name='person',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Session'),
        ),
    ]
