# Generated by Django 2.0.7 on 2018-07-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180703_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='session',
        ),
        migrations.AddField(
            model_name='person',
            name='session',
            field=models.ManyToManyField(to='api.Session'),
        ),
    ]
