# Generated by Django 2.0.7 on 2018-07-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_schedule_sponsor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='title',
            field=models.CharField(blank=True, max_length=127),
        ),
    ]
