# Generated by Django 2.0.7 on 2018-07-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180709_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='image_loc',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
