# Generated by Django 2.0.7 on 2018-07-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180717_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='linkedin',
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AddField(
            model_name='person',
            name='twitter',
            field=models.CharField(blank=True, max_length=63),
        ),
    ]
