# Generated by Django 2.0.7 on 2018-07-18 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180717_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='api.Schedule'),
        ),
    ]
