# Generated by Django 2.0.7 on 2018-07-20 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_session_schedule'),
        ('api', '0016_auto_20180718_1645'),
    ]

    operations = [
    ]
