# Generated by Django 2.0.7 on 2018-07-24 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merge_20180720_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session_Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_signedup', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='breakout_one',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='breakout_two',
        ),
        migrations.AddField(
            model_name='session',
            name='session_num',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session_attendee',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Attendee'),
        ),
        migrations.AddField(
            model_name='session_attendee',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Session'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='session',
            field=models.ManyToManyField(through='api.Session_Attendee', to='api.Session'),
        ),
    ]
