# Generated by Django 2.0.7 on 2018-07-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merge_20180720_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='max_capacity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='ppl_signed_up',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
