# Generated by Django 2.0.7 on 2018-07-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20180724_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='session_num',
        ),
        migrations.AddField(
            model_name='session',
            name='max_capacity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
