# Generated by Django 2.0.7 on 2018-07-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20180724_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_attendee',
            name='session_max_capacity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session_attendee',
            name='session_tag',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
