# Generated by Django 2.0.7 on 2018-07-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20180723_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorquery',
            name='name',
            field=models.CharField(blank=True, max_length=127),
        ),
    ]
