# Generated by Django 2.0.7 on 2018-07-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_sponsorquery_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsignup',
            name='name',
            field=models.CharField(blank=True, max_length=127),
        ),
    ]
