# Generated by Django 2.0.7 on 2018-07-31 15:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20180726_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='diet',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=63), size=4),
        ),
    ]
