# Generated by Django 2.0.7 on 2018-08-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20180731_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=models.CharField(blank=True, max_length=1023),
        ),
    ]
