# Generated by Django 2.0.7 on 2018-08-23 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_emailsignup_name'),
        ('api', '0022_auto_20180822_2229'),
    ]

    operations = [
    ]
