# Generated by Django 2.0.7 on 2018-09-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_attendee_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='session',
            field=models.ManyToManyField(blank=True, to='api.Session'),
        ),
    ]
