# Generated by Django 2.0.7 on 2018-09-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20180904_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='description',
            field=models.CharField(blank=True, max_length=1023),
        ),
    ]
