# Generated by Django 2.0.7 on 2018-09-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20180904_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='room_num',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
