# Generated by Django 2.0.7 on 2018-09-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20180904_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='hidden',
            field=models.BooleanField(default=True),
        ),
    ]
